apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validator
  template:
    metadata:
      labels:
        app: validator
    spec:
      containers:
        - name: validator
          image: 072245134533.dkr.ecr.us-east-2.amazonaws.com/fake-validator:latest
          command: ["/home/run.sh"]
          ports:
            - containerPort: 8085
              protocol: TCP
          resources:
            limits:
              aws.ec2.nitro/nitro_enclaves: "1"
              hugepages-1Gi: 24576Mi
              cpu: 250m
            requests:
              aws.ec2.nitro/nitro_enclaves: "1"
              hugepages-1Gi: 24576Mi
          volumeMounts:
            - mountPath: /dev/hugepages
              name: hugepage
              readOnly: false
      volumes:
        - name: hugepage
          emptyDir:
            medium: HugePages-1Gi
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists